In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
market_news_df = pd.read_excel('../Dataset/news_ratings/market_article_df_with_ratings.xlsx', parse_dates=['datetime'])
market_news_df.head()

,authors,datetime,description,source_url,title,url,summary,summary_vader,description_vader,summary_sentiment,description_sentiment
0,"['Sunil Shankar Matkar', 'Sunil Matkar']",2024-05-02 01:01:05,"A short build-up was seen in 52 stocks, includ...",https://www.moneycontrol.com,Trade setup for Thursday: 15 things to know be...,https://www.moneycontrol.com/news/business/mar...,The market took a U-turn from its lifetime hi...,0.5267,0.0000,1,1
1,"['Sai Aravindh', 'Live Tv', 'Stock Market', 'L...",2024-05-02 02:07:54,Market analysis suggests a further weakness fr...,https://www.ndtvprofit.com,Trade Setup For May 2: Nifty To See Further We...,https://www.ndtvprofit.com/markets/trade-setup...,The GIFT Nifty was trading 43 points or 0.19%...,0.9068,-0.1280,1,0
2,['Hormaz Fatakia'],2024-05-02 07:24:08,The Nifty corrected nearly 200 points from rec...,https://www.cnbctv18.com,Trade Setup for May 2: Nifty faces pressure at...,https://www.cnbctv18.com/market/trade-setup-ma...,Nifty faces pressure at higher levels ahead o...,0.7096,0.6597,1,0
3,['Asit Manohar'],2024-05-02 07:54:13,Trade setup for Thursday: In the US Fed meetin...,https://www.livemint.com,Stock market today: Trade setup for Nifty 50 a...,https://www.livemint.com/market/stock-market-n...,Trade setup for Nifty 50 after US Fed meeting...,0.8720,0.4019,2,1
4,['Hormaz Fatakia'],2024-05-02 21:45:22,"While Kotak Bank, ICICI Bank and Axis Bank kep...",https://www.cnbctv18.com,Trade Setup for May 3: Will heavyweight banks ...,https://www.cnbctv18.com/market/trade-setup-ma...,The Reserve Bank of India has lifted the rest...,-0.4019,0.4404,1,1

In [3]:
company_news_df = pd.read_excel('../Dataset/news_ratings/company_article_df_with_ratings.xlsx', parse_dates=['publishedAt'])
company_news_df.head()

,Unnamed: 0,source,authors,title,description,publishedAt,url,summary,companyName,source_url,summary_vader,description_vader,summary_sentiment,description_sentiment,companyTicker,market_cap_ratio
0,0,Forbes,"John Kang, Forbes Staff, \n John Kang, Forbes ...",Hyundai Motor India Shares Slump As Trading Be...,The South Korean car maker’s $3.3 billion shar...,2024-10-22 16:00:08,https://www.forbes.com/sites/johnkang/2024/10/...,Hyundai Motor India managing director Unsoo Ki...,Tata Motors,https://www.forbes.com,0.0000,0.2960,1,2,TATAMOTORS.NS,0.016092
1,1,Forbes,"Gloria Haraito, Forbes Staff, \n Gloria Harait...",What’s Driving The Son Of India’s Richest Woma...,"Amid India’s EV push, steel magnate Sajjan Jin...",2024-10-09 22:03:27,https://www.forbes.com/sites/gloriaharaito/202...,Sajjan (left) and Parth Jindal.\nJSW Group\nTh...,Tata Motors,https://www.forbes.com,0.7783,0.4767,2,2,TATAMOTORS.NS,0.016092
2,2,Livemint,George Skaria,Tata’s next challenge: Leadership void at Trusts,"With Ratan Tata’s passing, the lack of a clear...",2024-10-11 05:50:52,https://www.livemint.com/opinion/ratan-tata-de...,With the passing of Ratan Naval Tata (1937-202...,Tata Motors,https://www.livemint.com,0.0772,0.6486,1,0,TATAMOTORS.NS,0.016092
3,3,Business Standard,Dev Chatterjee,"Tata Capital, Tata Motors Finance merger recei...",Tata Capital-Tata Motors Finance Merger: Throu...,2024-10-14 13:41:19,https://www.business-standard.com/companies/ne...,"Through this merger, Tata Capital aims to attr...",Tata Motors,https://www.business-standard.com,0.4939,0.4939,2,2,TATAMOTORS.NS,0.016092
4,4,Livemint,Nikita Prasad,Ratan Tata passes away at 86: Top business tyc...,"Ratan Tata breathed his last on Wednesday, Oct...",2024-10-09 19:46:32,https://www.livemint.com/companies/people/rata...,"Ratan Tata passes away:Ratan Tata, chairman em...",Tata Motors,https://www.livemint.com,-0.3182,-0.1779,0,1,TATAMOTORS.NS,0.016092

In [4]:
set(market_news_df.columns)-set(company_news_df.columns)

{'datetime'}

In [5]:
set(company_news_df.columns)-set(market_news_df.columns)

{'Unnamed: 0',
 'companyName',
 'companyTicker',
 'market_cap_ratio',
 'publishedAt',
 'source'}

In [6]:
market_news_df['market_cap_ratio'] = 1
market_news_df.rename(columns={'datetime': 'publishedAt'}, inplace=True)
market_news_df[sorted(market_news_df.columns)].head()

,authors,description,description_sentiment,description_vader,market_cap_ratio,publishedAt,source_url,summary,summary_sentiment,summary_vader,title,url
0,"['Sunil Shankar Matkar', 'Sunil Matkar']","A short build-up was seen in 52 stocks, includ...",1,0.0000,1,2024-05-02 01:01:05,https://www.moneycontrol.com,The market took a U-turn from its lifetime hi...,1,0.5267,Trade setup for Thursday: 15 things to know be...,https://www.moneycontrol.com/news/business/mar...
1,"['Sai Aravindh', 'Live Tv', 'Stock Market', 'L...",Market analysis suggests a further weakness fr...,0,-0.1280,1,2024-05-02 02:07:54,https://www.ndtvprofit.com,The GIFT Nifty was trading 43 points or 0.19%...,1,0.9068,Trade Setup For May 2: Nifty To See Further We...,https://www.ndtvprofit.com/markets/trade-setup...
2,['Hormaz Fatakia'],The Nifty corrected nearly 200 points from rec...,0,0.6597,1,2024-05-02 07:24:08,https://www.cnbctv18.com,Nifty faces pressure at higher levels ahead o...,1,0.7096,Trade Setup for May 2: Nifty faces pressure at...,https://www.cnbctv18.com/market/trade-setup-ma...
3,['Asit Manohar'],Trade setup for Thursday: In the US Fed meetin...,1,0.4019,1,2024-05-02 07:54:13,https://www.livemint.com,Trade setup for Nifty 50 after US Fed meeting...,2,0.8720,Stock market today: Trade setup for Nifty 50 a...,https://www.livemint.com/market/stock-market-n...
4,['Hormaz Fatakia'],"While Kotak Bank, ICICI Bank and Axis Bank kep...",1,0.4404,1,2024-05-02 21:45:22,https://www.cnbctv18.com,The Reserve Bank of India has lifted the rest...,1,-0.4019,Trade Setup for May 3: Will heavyweight banks ...,https://www.cnbctv18.com/market/trade-setup-ma...

In [7]:
company_news_df.drop(columns=['Unnamed: 0', 'companyName', 'companyTicker', 'source'], inplace=True)
company_news_df[sorted(company_news_df.columns)].head()

,authors,description,description_sentiment,description_vader,market_cap_ratio,publishedAt,source_url,summary,summary_sentiment,summary_vader,title,url
0,"John Kang, Forbes Staff, \n John Kang, Forbes ...",The South Korean car maker’s $3.3 billion shar...,2,0.2960,0.016092,2024-10-22 16:00:08,https://www.forbes.com,Hyundai Motor India managing director Unsoo Ki...,1,0.0000,Hyundai Motor India Shares Slump As Trading Be...,https://www.forbes.com/sites/johnkang/2024/10/...
1,"Gloria Haraito, Forbes Staff, \n Gloria Harait...","Amid India’s EV push, steel magnate Sajjan Jin...",2,0.4767,0.016092,2024-10-09 22:03:27,https://www.forbes.com,Sajjan (left) and Parth Jindal.\nJSW Group\nTh...,2,0.7783,What’s Driving The Son Of India’s Richest Woma...,https://www.forbes.com/sites/gloriaharaito/202...
2,George Skaria,"With Ratan Tata’s passing, the lack of a clear...",0,0.6486,0.016092,2024-10-11 05:50:52,https://www.livemint.com,With the passing of Ratan Naval Tata (1937-202...,1,0.0772,Tata’s next challenge: Leadership void at Trusts,https://www.livemint.com/opinion/ratan-tata-de...
3,Dev Chatterjee,Tata Capital-Tata Motors Finance Merger: Throu...,2,0.4939,0.016092,2024-10-14 13:41:19,https://www.business-standard.com,"Through this merger, Tata Capital aims to attr...",2,0.4939,"Tata Capital, Tata Motors Finance merger recei...",https://www.business-standard.com/companies/ne...
4,Nikita Prasad,"Ratan Tata breathed his last on Wednesday, Oct...",1,-0.1779,0.016092,2024-10-09 19:46:32,https://www.livemint.com,"Ratan Tata passes away:Ratan Tata, chairman em...",0,-0.3182,Ratan Tata passes away at 86: Top business tyc...,https://www.livemint.com/companies/people/rata...

In [8]:
news_df = pd.concat([market_news_df, company_news_df], ignore_index=True)
news_df.sample(5)

,authors,publishedAt,description,source_url,title,url,summary,summary_vader,description_vader,summary_sentiment,description_sentiment,market_cap_ratio
5939,Gadgets 360 Staff,2024-10-24 11:48:24,Amazon Great Indian Festival Diwali Special 20...,https://www.gadgets360.com,Amazon Great Indian Festival Diwali Special 20...,https://www.gadgets360.com/internet/features/a...,Amazon Great Indian Festival Diwali Special 20...,0.8979,0.8979,2,2,0.043940
11324,Team BL,2024-10-14 01:00:19,"Sensex, Nifty, Share Prices: The Indian stock ...",https://www.thehindubusinessline.com,"Stock market highlights: Sensex, Nifty rally t...",https://www.thehindubusinessline.com/markets/s...,"<li></li>\nOctober 14, 2024 16:44Stock market ...",0.6908,0.8720,2,2,0.007216
440,[],2024-07-03 14:04:41,"The Sensex has breached the 80,000 mark, with ...",https://www.businesstoday.in,What Should Be Your Investment Strategy As Sen...,https://www.businesstoday.in/bt-tv/market-toda...,"Sensex Breaches 80,000 mark, Nifty reaches 24...",0.6582,0.9393,1,2,1.000000
3735,Beena Parmar,2024-10-20 00:31:00,"After a period of declining headcount, India's...",https://economictimes.indiatimes.com,IT sector’s top firms reverse headcount fall a...,https://economictimes.indiatimes.com/tech/info...,Five out of India's top six IT companiesTata C...,0.2023,0.6486,2,2,0.038392
11807,"Kurt Knutsson, CyberGuy Report",2024-10-07 14:00:33,"Kurt “CyberGuy"" Knutsson: Data breaches in 202...",https://www.foxnews.com,These are the 7 most devastating data breaches...,https://www.foxnews.com/tech/7-most-devastatin...,"In recent months, we've witnessed a shocking w...",-0.6590,0.0258,0,0,0.014301

In [9]:
def adjust_to_market_day(dt):
    # Shift to the previous day if before 9:30 AM
    if dt.time() < pd.Timestamp("09:30:00").time():
        return dt - pd.Timedelta(days=1)
    return dt

In [10]:
news_df['market_date'] = news_df['publishedAt'].apply(adjust_to_market_day).dt.date
news_df['summary_sentiment'] = news_df['summary_sentiment'].apply(lambda x: x - 1)
news_df['description_sentiment'] = news_df['description_sentiment'].apply(lambda x: x - 1)

In [11]:
def weighted_average(df, value_col, weight_col):
    return (df[value_col] * df[weight_col]).sum() / df[weight_col].sum()

In [12]:
cols = ['summary_vader', 'summary_sentiment', 'description_vader', 'description_sentiment']
grp = news_df.groupby('market_date')
agg_df = grp.apply(
    lambda x: pd.Series(
        {'news_count': x.shape[0]} | 
        {col: weighted_average(x, col, 'market_cap_ratio') for col in cols}
    )
).reset_index()
agg_df.tail()

/var/folders/8m/7v6gzd016pvd5cfs456xwjvc0000gn/T/ipykernel_29701/877638253.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  agg_df = grp.apply(

,market_date,news_count,summary_vader,summary_sentiment,description_vader,description_sentiment
173,2024-11-05,38.0,0.335390,-0.291963,0.335625,-0.424264
174,2024-11-06,61.0,0.460037,0.505029,0.438723,0.137617
175,2024-11-07,11.0,0.754730,0.880815,0.623004,-0.020865
176,2024-11-08,1.0,0.616600,-1.000000,0.000000,0.000000
177,2024-11-09,3.0,0.726733,0.000000,0.867767,0.000000

In [13]:
agg_df.to_csv('../Dataset/aggregated/aggregated_news_data.csv', index=False)